### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by tgy** [dadadel/pyment#30]
I am using `Python 3.6.0` and `Pyment v0.3.2`.

When running `pyment -c pyment.conf test.py` with

**pyment.conf**
```
first_line = true
quotes = '''
output_style = numpydoc
input_style = numpydoc
init2class = true
```

**test.py**
```python
def hello_world():
  return 42
```

I get the following error
```
Traceback (most recent call last):
  File "/home/toogy/.pyenv/versions/project/bin/pyment", line 11, in <module>
    load_entry_point('Pyment==0.3.2.dev0', 'console_scripts', 'pyment')()
  File "/home/toogy/.pyenv/versions/project/lib/python3.6/site-packages/Pyment-0.3.2.dev0-py3.6.egg/pyment/pymentapp.py", line 149, in main
  File "/home/toogy/.pyenv/versions/project/lib/python3.6/site-packages/Pyment-0.3.2.dev0-py3.6.egg/pyment/pymentapp.py", line 98, in run
  File "/home/toogy/.pyenv/versions/project/lib/python3.6/site-packages/Pyment-0.3.2.dev0-py3.6.egg/pyment/pyment.py", line 333, in proceed
  File "/home/toogy/.pyenv/versions/project/lib/python3.6/site-packages/Pyment-0.3.2.dev0-py3.6.egg/pyment/docstring.py", line 1942, in generate_docs
  File "/home/toogy/.pyenv/versions/project/lib/python3.6/site-packages/Pyment-0.3.2.dev0-py3.6.egg/pyment/docstring.py", line 1701, in _set_other
  File "/home/toogy/.pyenv/versions/project/lib/python3.6/site-packages/Pyment-0.3.2.dev0-py3.6.egg/pyment/docstring.py", line 308, in get_raw_not_managed
AttributeError: 'NoneType' object has no attribute 'split'
```

I think the `numpydoc` support is broken!

**edit**: I checked and this is also happening with `Python 3.5.2`

**Comment by tgy** [comment]
I submitted a solution: #31

**Comment by dadadel** [comment]
The issue is reached when the `input_style` is set to `numpydoc` and this even specified in command line option. Any other value for the input style won't crash Pyment.

**Comment by dadadel** [comment]
Thank you @tgy. Your PR fixed the issue. I added a test for it.
