### ISSUE TITLE
Problem to install on RHEL-7 (with python 2.7)

### ISSUE THREAD

**Issue by mcepl** [dadadel/pyment#35]
```
matej@mitmanek: pyment (master)$ python setup.py develop --user
running develop
running egg_info
writing Pyment.egg-info/PKG-INFO
writing top-level names to Pyment.egg-info/top_level.txt
writing dependency_links to Pyment.egg-info/dependency_links.txt
writing entry points to Pyment.egg-info/entry_points.txt
reading manifest file 'Pyment.egg-info/SOURCES.txt'
writing manifest file 'Pyment.egg-info/SOURCES.txt'
running build_ext
Creating /home/matej/.local/lib/python2.7/site-packages/Pyment.egg-link (link to .)
Adding Pyment 0.3.2.dev0 to easy-install.pth file
Installing pyment script to /home/matej/.local/bin

Installed /home/matej/archiv/knihovna/repos/pyment
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    'pyment = pyment.pymentapp:main'
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/develop.py", line 27, in run
    self.install_for_development()
  File "/usr/lib/python2.7/site-packages/setuptools/command/develop.py", line 129, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 701, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)
matej@mitmanek: pyment (master)$ 
```

**Comment by dadadel** [comment]
Hi @mcepl 
I plan to stop support for Python 2.7 in next release as it reached end of life last year.
Feel free to react to this in issue #97

**Comment by mcepl** [comment]
No problem, I have left Red Hat in meantime and my current employer (SUSE) doesn't carry this package at all (it seems).
